spring:
  datasource:
    username: 'db_user'
    password: '8b3b91c7'
    url: 'jdbc:mysql://localhost:3306/assessment'

  jpa:
    hibernate:
      ddl-auto: update


hostName: localhost
server:
  port: 8088